# Calamares Bootloader module configuration for Rain OS
---
efiBootLoader: "grub"
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: "5"

bootLoader:
  grubInstall: "grub-install"
  grubMkconfig: "grub-mkconfig"
  grubCfg: "/boot/grub/grub.cfg"
  grubProbe: "grub-probe"
  efiBootMgr: "efibootmgr"
  installEpoxyEnabled: true
