# Calamares Systemd Services configuration for Rain OS
---
services:
  - name: "NetworkManager"
    mandatory: false
  - name: "bluetooth"
    mandatory: false
  - name: "power-profiles-daemon"
    mandatory: false
  - name: "cups"
    mandatory: false
  - name: "sddm"
    mandatory: false
  - name: "fstrim.timer"
    mandatory: false
  - name: "systemd-timesyncd"
    mandatory: false
