# Rain OS Hyprland Theme: Tokyo Night (Rain)
general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgb(f7768e) rgb(f7768e) 45deg
    col.inactive_border = rgb(414868)
    layout = dwindle
}

decoration {
    rounding = 10
    active_opacity = 0.96
    inactive_opacity = 0.88
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        vibrancy = 0.1696
    }
    drop_shadow = true
    shadow_range = 15
    shadow_render_power = 3
    col.shadow = rgba(00000088)
}
