# Calamares configuration for Rain OS 1.3.0
---
modules-search: [ local ]

instances:
  - id:       rain-os
    module:   branding
    config:   branding.desc

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - packages
      - umount
  - show:
      - finished

branding: rain-os

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
