title    Rain OS Core (x86_64, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% archisosearchfilename=/%INSTALL_DIR%/x86_64/airootfs.sfs cow_spacesize=4G copytoram=n systemd.unit=graphical.target
