title    Rain OS Core LTS (x86_64, UEFI, Fallback)
sort-key 02
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% archisosearchfilename=/%INSTALL_DIR%/x86_64/airootfs.sfs cow_spacesize=4G copytoram=n irqpoll
