g autologin - -
u liveuser -:users "Rain Live User" /home/liveuser /bin/bash
m liveuser wheel
m liveuser video
m liveuser audio
m liveuser storage
m liveuser network
m liveuser power
m liveuser autologin
